/**
 * Validation of the TypeScript engine against the Python reference model.
 * Fixtures (harvest + trajectory checkpoints across 10 scenarios) were
 * generated by cho_cqa_model.py and frozen in __tests__/fixtures.json.
 */
import { describe, it, expect } from 'vitest';
import { simulate, defaultBioParams, defaultGlyParams, integrate, glyco, glyMods } from './engine';
import type { BioParams, Expression } from './types';
import fx from './__tests__/fixtures.json';

interface Fixture {
  titer: number; peakVCD: number; pCO2max: number;
  harvest: Record<string, number>;
  traj: Record<string, number[]>;
}
const fixtures = fx.fixtures as Record<string, Fixture>;

/** Rebuild the exact bio/gly/expr inputs for a named scenario. */
function scenarioInputs(name: string): { bio: BioParams; gly: ReturnType<typeof defaultGlyParams>; Mn: number; expr: Expression; mods: ReturnType<typeof glyMods> } {
  const bio = defaultBioParams();
  const gly = defaultGlyParams();
  let Mn = 0.5;
  let mods = glyMods({ Tset: 37, DO: 50, asn_level: 1 });
  const expr: Expression = { MGAT: 1, B4GALT: 1, FUT8: 1, ST6GAL: 1 };
  switch (name) {
    case 'low_strip': bio.kLa_CO2 = 0.06; break;
    case 'high_strip': bio.kLa_CO2 = 0.25; break;
    case 'Mn4x': Mn = 2.0; break;
    case 'gal_feed': bio.Fgal = 0.15; break;
    case 'fut8_kd': expr.FUT8 = 0.3; break;
    case 'st6_up': expr.ST6GAL = 4.0; break;
    case 'alkaline': bio.pH_set = 7.3; gly.pH_set = 7.3; break;
    case 'low_growth': bio.mu_max = 0.020; gly.mu_max = 0.020; break;
    case 'rich_feed': bio.Fglc = 0.5; bio.Fgln = 0.10; break;
    case 'asn_low': mods = glyMods({ Tset: 37, DO: 50, asn_level: 0.2 }); break;
    case 'do_low': mods = glyMods({ Tset: 37, DO: 15, asn_level: 1 }); break;
    case 'temp_shift': mods = glyMods({ Tset: 33, DO: 50, asn_level: 1 }); break;
  }
  return { bio, gly, Mn, expr, mods };
}

const REL = 0.02; // 2 % relative tolerance (RK4 vs LSODA + rounding)
const relClose = (a: number, b: number, tol = REL) => Math.abs(a - b) <= tol * (Math.abs(b) + 1e-6);

describe('bioreactor integrator', () => {
  it('conserves non-negativity and produces a growth peak', () => {
    const R = integrate(defaultBioParams(), 13);
    const Xv = R.y[0];
    expect(Math.min(...Xv)).toBeGreaterThanOrEqual(0);
    expect(Math.max(...Xv)).toBeGreaterThan(10);
  });
});

describe('TS engine matches Python reference (harvest CQAs)', () => {
  for (const name of Object.keys(fixtures)) {
    it(name, () => {
      const { bio, gly, Mn, expr, mods } = scenarioInputs(name);
      const r = simulate(bio, gly, Mn, expr, 13, mods);
      const f = fixtures[name];
      expect(relClose(r.titer, f.titer)).toBe(true);
      expect(relClose(r.peakVCD, f.peakVCD)).toBe(true);
      expect(relClose(r.pCO2max, f.pCO2max)).toBe(true);
      for (const k of Object.keys(f.harvest)) {
        const got = (r.harvest as Record<string, number>)[k];
        expect(relClose(got, f.harvest[k], 0.03),
          `${name}.${k}: got ${got.toFixed(3)} want ${f.harvest[k].toFixed(3)}`).toBe(true);
      }
    });
  }
});

describe('TS engine matches Python reference (trajectory checkpoints)', () => {
  for (const name of Object.keys(fixtures)) {
    it(`${name} trajectory`, () => {
      const { bio, gly, Mn, expr, mods } = scenarioInputs(name);
      const r = simulate(bio, gly, Mn, expr, 13, mods);
      const f = fixtures[name];
      const days = [0, 3, 6, 9, 12];
      const idx = days.map((d) => d * 24);
      idx.forEach((ix, di) => {
        expect(relClose(r.pCO2[ix], f.traj.pCO2[di], 0.03)).toBe(true);
        expect(relClose(r.cqaT.G0F[ix], f.traj.G0F[di], 0.03)).toBe(true);
        expect(relClose(r.cqaT.galactosylation[ix], f.traj.galactosylation[di], 0.03)).toBe(true);
      });
    });
  }
});

describe('mechanistic monotonicities (mechanism sanity)', () => {
  const run = (over: Partial<{ kLa: number; fut8: number; mn: number }>) => {
    const bio = defaultBioParams(); const gly = defaultGlyParams();
    if (over.kLa) bio.kLa_CO2 = over.kLa;
    const expr: Expression = { MGAT: 1, B4GALT: 1, FUT8: over.fut8 ?? 1, ST6GAL: 1 };
    return simulate(bio, gly, over.mn ?? 0.5, expr, 13);
  };

  it('poor CO2 stripping raises dissolved pCO2', () => {
    expect(run({ kLa: 0.06 }).pCO2max).toBeGreaterThan(run({ kLa: 0.25 }).pCO2max);
  });

  // The pH -> galactosylation mechanism is monotonic only at FIXED Golgi residence.
  // Isolate it at the enzyme-network level (glyco) holding mu constant, so the
  // growth->residence confound present in the harvest rollup is removed.
  it('at fixed residence, higher pCO2 (lower Golgi pH) lowers galactosylation', () => {
    const gly = defaultGlyParams();
    const base = {
      mu: 0.012, Mn: 0.5, UDPGlcNAc: 1, UDPGal: 1, GDPFuc: 1, CMPNeuAc: 1,
      MGAT: 1, B4GALT: 1, FUT8: 1, ST6GAL: 1,
    };
    const lowCO2 = glyco({ ...base, pCO2: 40 }, gly).cqa;
    const highCO2 = glyco({ ...base, pCO2: 130 }, gly).cqa;
    expect(highCO2.pH_golgi).toBeLessThan(lowCO2.pH_golgi);
    expect(highCO2.galactosylation).toBeLessThan(lowCO2.galactosylation);
    expect(highCO2.high_mannose).toBeGreaterThan(lowCO2.high_mannose);
  });

  // At the harvest level the net effect of poor stripping on galactosylation is
  // small and can invert, because slower growth lengthens residence (documented
  // model behaviour, not a bug) — assert only that the net shift stays modest.
  it('poor CO2 stripping has a bounded net effect on harvest galactosylation', () => {
    const good = run({ kLa: 0.25 }), bad = run({ kLa: 0.06 });
    expect(Math.abs(bad.harvest.galactosylation - good.harvest.galactosylation)).toBeLessThan(5);
  });

  it('FUT8 knockdown raises afucosylation', () => {
    expect(run({ fut8: 0.3 }).harvest.afucosylation).toBeGreaterThan(run({ fut8: 1 }).harvest.afucosylation);
  });
  it('Mn2+ supplementation raises galactosylation', () => {
    expect(run({ mn: 2.0 }).harvest.galactosylation).toBeGreaterThan(run({ mn: 0.5 }).harvest.galactosylation);
  });
});

describe('extended inputs preserve baseline and move CQAs in the documented direction', () => {
  const bio = defaultBioParams(), gly = defaultGlyParams();
  const expr: Expression = { MGAT: 1, B4GALT: 1, FUT8: 1, ST6GAL: 1 };
  const base = () => simulate(bio, gly, 0.5, expr, 13, glyMods({ Tset: 37, DO: 50, asn_level: 1 }));

  it('default modifiers reproduce the baseline exactly', () => {
    const a = simulate(bio, gly, 0.5, expr, 13);
    const b = base();
    for (const k of Object.keys(a.harvest) as (keyof typeof a.harvest)[]) {
      expect(Math.abs(a.harvest[k] - b.harvest[k])).toBeLessThan(1e-9);
    }
  });
  it('temperature downshift (37->33) raises galactosylation via longer residence', () => {
    const cool = simulate(bio, gly, 0.5, expr, 13, glyMods({ Tset: 33, DO: 50, asn_level: 1 }));
    expect(cool.harvest.galactosylation).toBeGreaterThan(base().harvest.galactosylation);
  });
  it('asparagine depletion raises high-mannose', () => {
    const dep = simulate(bio, gly, 0.5, expr, 13, glyMods({ Tset: 37, DO: 50, asn_level: 0.2 }));
    expect(dep.harvest.high_mannose).toBeGreaterThan(base().harvest.high_mannose);
  });
  it('low DO lowers sialylation', () => {
    const lowDO = simulate(bio, gly, 0.5, expr, 13, glyMods({ Tset: 37, DO: 15, asn_level: 1 }));
    expect(lowDO.harvest.sialylation).toBeLessThan(base().harvest.sialylation);
  });
});
